apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yml
# - deployment.yml
- db-config.yml
# - service.yml
- migration-job.yml
- serverless-service.yml
- domain-claim.yml
- domain-mapping.yml