apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/argocd-applications/argocd.yml
- manifests/argocd-applications/istio-operator.yml
- manifests/argocd-applications/istio.yml
- manifests/argocd-applications/cert-manager.yml
- manifests/argocd-applications/istio-resources.yml
- manifests/argocd-applications/certificates.yml
- manifests/argocd-applications/webapp.yml
- manifests/argocd-applications/knative.yml